#!/bin/bash
# Script for downloading and installing the latest version of atom.

set -eu

# TODO: Check if newer version is available before proceeding.

rm -f /tmp/atom.deb
curl -L https://atom.io/download/deb > /tmp/atom.deb
sudo dpkg --install /tmp/atom.deb
apm upgrade --confirm false
