#!/bin/bash
# Update atom from downloaded deb file

#TODO Safely kill current atom processes

rm -f /tmp/atom.deb
curl -L https://atom.io/download/deb > /tmp/atom.deb
dpkg --install /tmp/atom.deb

apm upgrade --confirm false

exit 0
