#!/bin/bash
# Script for downloading and installing the latest version of atom.

set -eu

procCount=$(pgrep -c atom)
# The current shell process also includes the keyword "atom".
if  [[ $procCount -ne 1 ]] ; then
    echo "Close all existing atom instances to continue."
    exit 1
fi

# TODO: Check if newer version is available before proceeding.

rm -f /tmp/atom.deb
curl -L https://atom.io/download/deb > /tmp/atom.deb
sudo dpkg --i /tmp/atom.deb
apm upgrade --confirm false
