#!/bin/bash

set -eu

die() {
  echo "$@"
  exit 1
}

# Check for root privileges
[[ "$(id -u)" != "0" ]] && {
  sudo "$0" "$@"
  exit $?
}

if [ -d /sys/class/backlight/intel_backlight ]; then
  brightness_directory="/sys/class/backlight/intel_backlight"
elif [ -d /sys/class/blacklight/acpi_video0 ]; then
  brightness_directory="/sys/class/backlight/acpi_video0"
else
  die "Can't determine backlight controller"
fi

current_brightness=$(< $brightness_directory/brightness)

if [[ $# -eq 0 ]]; then
  echo "$current_brightness" && exit
elif [[ $1 == '=' && $# -ne 2 ]]; then
  die "USAGE: brightness = <integer>"
elif [[ $1 != '=' && $# -ne 1 ]]; then
  die "USAGE: brightness (+/-)<integer>"
fi

max_brightness=$(< $brightness_directory/max_brightness)

if [[ "$1" == "=" ]]; then
  brightness=$2
else
  brightness=$1
  brightness=$((current_brightness + brightness))
fi

# $brightness ∈ [1, $max_brightness]
if [[ $brightness -lt 1 ]]; then
  brightness=1
elif [[ $brightness -gt $max_brightness ]]; then
  brightness=$max_brightness
fi

echo "$brightness" > "$brightness_directory/brightness"
