#!/bin/bash

die(){
  echo "$@"
  exit 1
}

# Check for root priviledges
[[ "$(id -u)" != "0" ]] && {
  sudo "$0" "$@"
  exit $?
}

brightness_directory="/sys/class/backlight/intel_backlight"
current_brightness=$(cat $brightness_directory/brightness)

if [[ $# -eq 0 ]]; then
  echo "$current_brightness" && exit
elif [[ $1 == '=' && $# -ne 2 ]]; then
  die "USAGE: brightness = <integer>"
elif [[ $# -ne 0 && $# -ne 1 ]]; then
  die "USAGE: brightness <integer>"
fi

##########################
## Compatibility checks ##
##########################

# if [ -d /sys/class/backlight/intel_backlight ]; then
#   brightness_directory="/sys/class/backlight/intel_backlight"
# elif [ -d /sys/class/blacklight/acpi_video0 ]; then
#   brightness_directory="/sys/class/backlight/acpi_video0"
# else
#   die "Can't determine backlight controller"
# fi

max_brightness=$(cat $brightness_directory/max_brightness)

if [[ "$1" == "=" ]]; then
  brightness=$2
else
  brightness=$1
  brightness=$((current_brightness + brightness))
fi

# 1 <= $brightness <= $max_brightness
if [[ $brightness -lt 0 ]] || [[ $brightness -eq 0 ]]; then
  brightness=1
elif [[ $brightness -gt $max_brightness ]]; then
  brightness=$max_brightness
fi

echo "$brightness" > "$brightness_directory/brightness"
