#!/bin/bash
# Utility script for viewing results of a C++ program in a single step.

file=$*
bin="a.out"
CC=g++

trap cleanup INT

cleanup() {
    rm -f "$bin"
}

main() {
    $CC $file && ./"$bin"
    cleanup
}

if [[ "$#" -ne 1 ]]; then
    echo "usage: cppcompile <cpp-file>"
    exit 1
fi

main
