#!/bin/bash
# Ref: https://github.com/idank/explainshell/issues/4#issuecomment-354709120

set -euo pipefail

if [ $# -eq 0 ]; then
    exit 0
fi

# Here strings are noted to be faster for a small amount of
# data as compared to pipes where the setup cost dominates.
# https://unix.stackexchange.com/a/219806/158139
response=$(w3m -dump "http://explainshell.com/explain?cmd="$(echo $@ | tr ' ' '+'}))
columns=$(tput cols)
cat -s <(grep -v -e explainshell -e • -e □ -e "source manpages" <<< "$response") | fmt -w $columns
